### ISSUE TITLE
Incorrect condition when choosing to show or not UIAlertController

### ISSUE THREAD

**Issue by uniqby** [janlionly/AvatarImagePicker#1]
```
if sourceTypes.count **> 2** {
 // showing UIAlertController
} else {
}
```

should be **sourceTypes.count > 1** instead of **> 2**

**Comment by janlionly** [comment]
> ```
> if sourceTypes.count **> 2** {
>  // showing UIAlertController
> } else {
> }
> ```
> 
> should be **sourceTypes.count > 1** instead of **> 2**

fixed, thanks.
