### ISSUE TITLE
Crash in iPad

### ISSUE THREAD

**Issue by seniorlancer** [janlionly/AvatarImagePicker#2]
This was crashed in iPad. Because the following code doesn't work on iPad.
`var sheet = UIAlertController(title: nil, message: nil, preferredStyle: .actionSheet)`
So I fixed this like following
`var sheet = UIAlertController(title: nil, message: nil, preferredStyle: .actionSheet)
if (UIDevice.current.userInterfaceIdiom == .pad) {
   sheet = UIAlertController(title: nil, message: nil, preferredStyle: .alert)
}`

**Comment by janlionly** [comment]
> This was crashed in iPad. Because the following code doesn't work on iPad.
> `var sheet = UIAlertController(title: nil, message: nil, preferredStyle: .actionSheet)`
> So I fixed this like following
> `var sheet = UIAlertController(title: nil, message: nil, preferredStyle: .actionSheet) if (UIDevice.current.userInterfaceIdiom == .pad) { sheet = UIAlertController(title: nil, message: nil, preferredStyle: .alert) }`

Hi, Seniorlancer, fixed it on iPad, Thanks so much.
